name: Doro Docker Runner

on:
  schedule:
    - cron: '15 * * * *'  # Runs every hour
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-doro:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # 5 hours 50 minutes
    steps:
      - name: Run Doro Docker Image
        run: |
          docker run \
            --cap-add=NET_ADMIN \
            --device=/dev/net/tun \
            derosato/doro
